### ISSUE TITLE
Tasks for Nov/Dec 2018

### ISSUE THREAD

**Issue by ClemensWittenbecher** [ClemensWittenbecher/NetCoupler#24]
# To do

tasks due | Clemens | Luke | Helena
-- | -- | -- | --
until Friday 11/2 | Preselect potential network-estimation algorithms; propose simulation procedures |   |  
until Friday 11/9 | Propose code to simulate toy data for tests | Implement *nc_create_network* function | Contribute to Luke's task mostly?
until Friday 11/16 | Simulate data; Test *nc_create_network* function with simulated data | Simulate data; Test *nc_create_network* function with simulated data; adjust *nc_create_network* function output to   smoothly serve as Input for NC functions | Contribute to Luke's task mostly?
until Friday 11/23 | Generally define how the output (results) of the *nc_outcome_estimates* function should look like (probably different options in terms of provided details) | Implement Input-related check functions in *nc_outcome_estimates* enduser-function, Test and identify efficiency issues of the *nc_outcome_estimates* function | Contribute to Luke's task mostly?
until Friday 11/30 | Summarize already implemented get.functions with reference to the output options that were discussed | Work on computational optimization | Contribute to Luke's task mostly?
until Friday 12/07 | Adjust get.functions to produce the intended outputs | Work on computational optimization; adjust get.functions to produce the intended outputs | Contribute to Luke's task mostly?
until Friday 12/14 | Test *nc_outcome_estimates* function; review code to submit results as network file to cytoscape | Test *nc_outcome_estimates* function ; adjust get.functions to produce the intended outputs | Contribute to Luke's task mostly?

These tasks are related to #22 and #23 

Additional tasks:

- Learn Git and GitHub workflow

**Comment by ClemensWittenbecher** [comment]
# Weekly meetings 
## Schedules & preliminary agenda


Meeting | Task 1 | Task 2
-- | -- | --
Friday 11/2 | Discuss network estimation procedure (i.e. causal structure learning); choose package(s)/code to serve as basis for *nc_create_network* function | Define simulation strategy
Friday 11/9 | Progress report *nc_create_network* function | Discuss/share simulation code
Friday 11/16 | Define final test dataset(s) | Discuss link between *nc_create_network* and *nc_outcome_estimates* functions
Friday 11/23 | Discuss efficiency issues of *nc_outcome_estimates* function and define solution strategy | Discuss output options for *nc_outcome_estimates* 
Friday 11/30 | Identify issues for get.functions | Progress report computational optimization
Friday 12/07 | Progress report customized outputs (results) | Progress report computational optimization
Friday 12/14 | Wrap up results: Do we have a convenient solution to link metabolomics networks to survival-time data? Which issues remain? | Discuss tasks and schedule for Jan/Feb 2019

**Comment by ClemensWittenbecher** [comment]
Please comment and change!

**Comment by lwjohnst86** [comment]
I can already say that these timelines are very ambitious, at least for my end. I'll start seeing how long things take and update the timelines accordingly.

**Comment by ClemensWittenbecher** [comment]
Tell me about things taking longer than initially thought... Do you think a weekly meeting is too much or are you rather referring to the tasks? For me it would be quite important to define some timeline because I have to split my attention between so many projects at the moment and I want to make sure that I resererve some time for this one.

**Comment by lwjohnst86** [comment]
A weekly meeting is fine actually. That would keep things at least progressing fairly well. And we can adjust as needed. What time Friday? I could meet at around 1130. Or before 15.

**Comment by ClemensWittenbecher** [comment]
11:30 works for me. So I leave things as they are, and we will adjust the plans after our meeting, right?

See you!



>>> Luke W Johnston <notifications@github.com> 29.10.2018 12:05 >>>
A weekly meeting is fine actually. That would keep things at least progressing fairly well. And we can adjust as needed. What time Friday? I could meet at around 1130. Or before 15.

**Comment by lwjohnst86** [comment]
Done. See you 1130 Friday.
